#!/usr/bin/env bash
set -e

# get latest version of Delly from github
git clone --recursive https://github.com/dellytools/delly.git

cd delly/

# Build with OpenMP API
make PARALLEL=1 src/delly


# install code ocean aux tools
mkdir -p /opt
cd /opt
git clone https://github.com/codeocean/co_aux_tools.git
cd co_aux_tools/
chmod +x {g,s}et_*
ln -s $PWD/{g,s}et_*.py /usr/local/bin
